### ISSUE TITLE
Unable to use Prometheus for Alerts on container provider (OCP4.x)

### ISSUE THREAD

**Issue by bsogithub** [ManageIQ/manageiq-providers-openshift#177] opened 2020-05-14 14:03 UTC
The container provide is connected to OCP 4.3.13. When trying to detect the hostname/ip, there is an error:
![image](https://user-images.githubusercontent.com/29459925/81939938-fe40a700-95c4-11ea-83bd-b46abab9ee92.png)

Using the following command, I found the prometheus-k8s service:
oc -n openshift-monitoring get routes
NAME HOST/PORT PATH SERVICES PORT TERMINATION WILDCARD
...
prometheus-k8s prometheus-k8s-openshift-monitoring.apps.cp4mcm-pen.os.fyre.ibm.com prometheus-k8s web reencrypt/Redirect None

Using nmap to list the https and http port and they are used with the hostname. However, the Validate does not give any error message on either port:
![image](https://user-images.githubusercontent.com/29459925/81942963-d0f5f800-95c8-11ea-932e-6ccc87915d39.png)

Metrices  can use Prometheus but not Alerts

**Comment by Fryguy** [comment] 2020-05-14 14:05
@bsogithub What version of ManageIQ are you using?

**Comment by bsogithub** [comment] 2020-05-14 16:13
@Fryguy Can't confirm now. Brad is updating the system. I will try again once he has the env up.

**Comment by chessbyte** [comment] 2020-05-14 16:15
@agrare @Fryguy is this issue addressed by this [PR](https://github.com/ManageIQ/manageiq-providers-openshift/pull/174) (which probably should be backported to Jansa)?

**Comment by agrare** [comment] 2020-05-14 16:19
The get_route error is fixed by that and I can confirm that Prometheus metrics works with the current core.

I think this issue really is for Prometheus alert which looks like what we have for OCP v3 doesn't work on OCP v4 it isn't just a hostname change.

**Comment by cben** [comment] 2020-05-15 03:38
I think there was a process called "alert manager buffer" that had to run, but don't remember on which side (openshift or miq) (?)

**Comment by agrare** [comment] 2020-05-15 15:23
Oh you're right @cben https://github.com/openshift/prometheus-alert-buffer thanks!

@bsogithub can you make sure that you have the alert buffer properly configured?  It seems that credential verification failing is accurate in this case.

**Comment by agrare** [comment] 2020-05-18 13:58
I think the main issue here is that we are auto-detecting that service expecting it to be the old v3 alert buffer but that isn't installed by default on ocpv4, so we shouldn't auto-detect it.

**Closed** 2020-05-18 15:09 UTC
Labels: bug

**Comment by bsogithub** [comment] 2020-05-19 16:35
@agrare The readme on https://github.com/openshift/prometheus-alert-buffer is not very clear to me. It has the following information:
This simple server accepts incoming JSON objects over HTTP, stores them in a database, and makes them queryable by index via HTTP.
Build
go build
Run
./prometheus-alert-buffer

Do I just run build.sh or run go build main.go? I could not find prometheus-alert-buffer. May be it is created after the 'build'? Could you please help?

**Comment by chessbyte** [comment] 2020-05-19 20:01
@bsogithub should be (somehow) a part of OpenShift

**Comment by agrare** [comment] 2020-05-20 13:07
Hey @bsogithub the `Openshift::MonitoringManager` requires the PrometheusAlertBuffer to be running on the cluster.  This was installed by default in OCP v3.x but not on OCP v4.  It might be possible to install it on OCP v4 but I haven't done it personally, if so then our MonitoringManager would work.  Out of the box it will not work however which is why we disabled auto-detection of the alerts endpoint.

OCP v4 users a new prometheus alert manager https://prometheus.io/docs/alerting/alertmanager/ with a different API.  It would be a nice enhancement to support this but we do not support it currently.
